apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
  labels:
    app: hiring-app
spec:
  selector:
    app: hiring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

